config/routes.rb
Rails.application.routes.draw do
  resources :seasons
  resources :tribes
  resources :drafters
  resources :survivors
  devise_for :users

  root 'survivors#index'

end

app/models/survivor.rb
class Survivor < ActiveRecord::Base
  has_and_belongs_to_many :drafters
  has_and_belongs_to_many :seasons
  has_and_belongs_to_many :tribes
end

app/controllers/survivors_controller.rb
class SurvivorsController < ApplicationController
  before_action :authenticate_user!, :set_survivor, only: [:show, :edit, :update, :destroy]

  # GET /survivors
  # GET /survivors.json
  def index
    @survivors = Survivor.all
  end

  # GET /survivors/1
  # GET /survivors/1.json
  def show
  end

  # GET /survivors/new
  def new
    @survivor = Survivor.new
    @seasons = Season.all
    @survivors = Survivor.all
  end

  # GET /survivors/1/edit
  def edit
    @seasons = Season.all
    @tribes = Tribe.all
  end

  # POST /survivors
  # POST /survivors.json
  def create
    @survivor = Survivor.new(survivor_params)

    respond_to do |format|
      if @survivor.save
        format.html { redirect_to @survivor, notice: 'Survivor was successfully created.' }
        format.json { render :show, status: :created, location: @survivor }
      else
        format.html { render :new }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survivors/1
  # PATCH/PUT /survivors/1.json
  def update
    respond_to do |format|
      if @survivor.update(survivor_params)
        format.html { redirect_to @survivor, notice: 'Survivor was successfully updated.' }
        format.json { render :show, status: :ok, location: @survivor }
      else
        format.html { render :edit }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survivors/1
  # DELETE /survivors/1.json
  def destroy
    @survivor.destroy
    respond_to do |format|
      format.html { redirect_to survivors_url, notice: 'Survivor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survivor
      @survivor = Survivor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survivor_params
      params.require(:survivor).permit(:name, :age, :residence, :photo_url, :fantasy, :elimination_number,
                                       :season_ids => [], :tribe_ids => [])
    end
end

app/helpers/survivors_helper.rb
module SurvivorsHelper
end

app/views/survivors/_form.html.erb
<%= simple_form_for(@survivor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :residence %>
    <%= f.input :photo_url %>
    <%= f.input :fantasy %>
    <%= f.input :elimination_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/survivors/edit.html.erb
<h1>Editing Survivor</h1>

<%= render 'form' %>

<%= link_to 'Show', @survivor %> |
<%= link_to 'Back', survivors_path %>

app/views/survivors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Survivors</h1>

<table class="table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Residence</th>
      <th>Photo url</th>
      <th>Elimination number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survivors.each do |survivor| %>
      <tr>
        <td><%= survivor.name %></td>
        <td><%= survivor.age %></td>
        <td><%= survivor.residence %></td>
        <td><%= image_tag survivor.photo_url %></td>
        <td><%= survivor.elimination_number %></td>
        <td><%= link_to 'Show', survivor %></td>
        <td><%= link_to 'Edit', edit_survivor_path(survivor) %></td>
        <td><%= link_to 'Destroy', survivor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survivor', new_survivor_path %>

app/views/survivors/new.html.erb
<h1>New Survivor</h1>

<%= render 'form' %>

<%= link_to 'Back', survivors_path %>

app/views/survivors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survivor.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @survivor.age %>
</p>

<p>
  <strong>Residence:</strong>
  <%= @survivor.residence %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @survivor.photo_url %>
</p>

<p>
  <strong>Fantasy:</strong>
  <%= @survivor.fantasy %>
</p>

<p>
  <strong>Elimination number:</strong>
  <%= @survivor.elimination_number %>
</p>

<%= link_to 'Edit', edit_survivor_path(@survivor) %> |
<%= link_to 'Back', survivors_path %>