config/routes.rb
Rails.application.routes.draw do
  resources :seasons
  resources :tribes
  resources :drafters
  resources :survivors
  devise_for :users

  root 'survivors#index'

end

app/models/tribe.rb
class Tribe < ActiveRecord::Base
  has_and_belongs_to_many :survivors
end

app/controllers/tribes_controller.rb
class TribesController < ApplicationController
  before_action :authenticate_user!, :set_tribe, only: [:show, :edit, :update, :destroy]

  # GET /tribes
  # GET /tribes.json
  def index
    @tribes = Tribe.all
  end

  # GET /tribes/1
  # GET /tribes/1.json
  def show
  end

  # GET /tribes/new
  def new
    @tribe = Tribe.new
    @survivors = Survivor.all
  end

  # GET /tribes/1/edit
  def edit
    @survivors = Survivor.all
  end

  # POST /tribes
  # POST /tribes.json
  def create
    @tribe = Tribe.new(tribe_params)

    respond_to do |format|
      if @tribe.save
        format.html { redirect_to @tribe, notice: 'Tribe was successfully created.' }
        format.json { render :show, status: :created, location: @tribe }
      else
        format.html { render :new }
        format.json { render json: @tribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tribes/1
  # PATCH/PUT /tribes/1.json
  def update
    respond_to do |format|
      if @tribe.update(tribe_params)
        format.html { redirect_to @tribe, notice: 'Tribe was successfully updated.' }
        format.json { render :show, status: :ok, location: @tribe }
      else
        format.html { render :edit }
        format.json { render json: @tribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tribes/1
  # DELETE /tribes/1.json
  def destroy
    @tribe.destroy
    respond_to do |format|
      format.html { redirect_to tribes_url, notice: 'Tribe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tribe
      @tribe = Tribe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tribe_params
      params.require(:tribe).permit(:name, :tribe_generation, :immunity_wins, :reward_wins, :survivor_ids => [])
    end
end

app/helpers/tribes_helper.rb
module TribesHelper
end

app/views/tribes/_form.html.erb
<%= simple_form_for(@tribe) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :tribe_generation %>
    <%= f.input :immunity_wins %>
    <%= f.input :reward_wins %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tribes/edit.html.erb
<h1>Editing Tribe</h1>

<%= render 'form' %>

<%= link_to 'Show', @tribe %> |
<%= link_to 'Back', tribes_path %>

app/views/tribes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tribes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tribe generation</th>
      <th>Immunity wins</th>
      <th>Reward wins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tribes.each do |tribe| %>
      <tr>
        <td><%= tribe.name %></td>
        <td><%= tribe.tribe_generation %></td>
        <td><%= tribe.immunity_wins %></td>
        <td><%= tribe.reward_wins %></td>
        <td><%= link_to 'Show', tribe %></td>
        <td><%= link_to 'Edit', edit_tribe_path(tribe) %></td>
        <td><%= link_to 'Destroy', tribe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tribe', new_tribe_path %>

app/views/tribes/new.html.erb
<h1>New Tribe</h1>

<%= render 'form' %>

<%= link_to 'Back', tribes_path %>

app/views/tribes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tribe.name %>
</p>

<p>
  <strong>Tribe generation:</strong>
  <%= @tribe.tribe_generation %>
</p>

<p>
  <strong>Immunity wins:</strong>
  <%= @tribe.immunity_wins %>
</p>

<p>
  <strong>Reward wins:</strong>
  <%= @tribe.reward_wins %>
</p>

<%= link_to 'Edit', edit_tribe_path(@tribe) %> |
<%= link_to 'Back', tribes_path %>