config/routes.rb
Rails.application.routes.draw do
  resources :seasons
  resources :tribes
  resources :drafters
  resources :survivors
  devise_for :users

  root 'survivors#index'

end

app/models/drafter.rb
class Drafter < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :survivors
end

app/controllers/drafters_controller.rb
class DraftersController < ApplicationController
  before_action :authenticate_user!, :set_drafter, only: [:show, :edit, :update, :destroy]

  # GET /drafters
  # GET /drafters.json
  def index
    @drafters = Drafter.all
  end

  # GET /drafters/1
  # GET /drafters/1.json
  def show
  end

  # GET /drafters/new
  def new
    @drafter = Drafter.new
    @survivors = Survivor.all
  end

  # GET /drafters/1/edit
  def edit
    @survivors = Survivor.all
  end

  # POST /drafters
  # POST /drafters.json
  def create
    @drafter = Drafter.new(drafter_params)

    respond_to do |format|
      if @drafter.save
        format.html { redirect_to @drafter, notice: 'Drafter was successfully created.' }
        format.json { render :show, status: :created, location: @drafter }
      else
        format.html { render :new }
        format.json { render json: @drafter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drafters/1
  # PATCH/PUT /drafters/1.json
  def update
    respond_to do |format|
      if @drafter.update(drafter_params)
        format.html { redirect_to @drafter, notice: 'Drafter was successfully updated.' }
        format.json { render :show, status: :ok, location: @drafter }
      else
        format.html { render :edit }
        format.json { render json: @drafter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drafters/1
  # DELETE /drafters/1.json
  def destroy
    @drafter.destroy
    respond_to do |format|
      format.html { redirect_to drafters_url, notice: 'Drafter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drafter
      @drafter = Drafter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drafter_params
      params.require(:drafter).permit(:user_id, :wins, :losses, :survivor_ids => [])
    end
end

app/helpers/drafters_helper.rb
module DraftersHelper
end

app/views/drafters/_form.html.erb
<%= simple_form_for(@drafter) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :wins %>
    <%= f.input :losses %>
    <%= f.association :survivors, as: :check_boxes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/drafters/edit.html.erb
<h1>Editing Drafter</h1>

<%= render 'form' %>

<%= link_to 'Show', @drafter %> |
<%= link_to 'Back', drafters_path %>

app/views/drafters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drafters</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Wins</th>
      <th>Losses</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drafters.each do |drafter| %>
      <tr>
        <td><%= drafter.user.name %></td>
        <td><%= drafter.wins %></td>
        <td><%= drafter.losses %></td>
        <td><%= link_to 'Show', drafter %></td>
        <td><%= link_to 'Edit', edit_drafter_path(drafter) %></td>
        <td><%= link_to 'Destroy', drafter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drafter', new_drafter_path %>

app/views/drafters/new.html.erb
<h1>New Drafter</h1>

<%= render 'form' %>

<%= link_to 'Back', drafters_path %>

app/views/drafters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @drafter.user.name %>
</p>

<p>
  <strong>Wins:</strong>
  <%= @drafter.wins %>
</p>

<p>
  <strong>Losses:</strong>
  <%= @drafter.losses %>
</p>

<h1>Listing Survivors</h1>

<table class="table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Photo url</th>
    <th>Elimination number</th>
  </tr>
  </thead>

  <tbody>
  <% @drafter.survivors.each do |survivor| %>
      <tr>
        <td><%= survivor.name %></td>
        <td><%= image_tag survivor.photo_url %></td>
        <td><%= survivor.elimination_number %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_drafter_path(@drafter) %> |
<%= link_to 'Back', drafters_path %>